"""add published_curriculum

Revision ID: 4c91948529fc
Revises: 0005
Create Date: 2026-09-15 00:35:58.484612+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c91948529fc'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_curriculum',
    sa.Column('published_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('module_outline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('published_id'),
    sa.UniqueConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published_curriculum')
    # ### end Alembic commands ###
