"""add_llm_call_record

Revision ID: fcca13eed77d
Revises: 947af982017a
Create Date: 2026-09-16 13:16:07.013446+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fcca13eed77d'
down_revision: str | None = '947af982017a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_record',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_llm_call_record_correlation_id'), 'llm_call_record', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_llm_call_record_thread_id'), 'llm_call_record', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_call_record_thread_id'), table_name='llm_call_record')
    op.drop_index(op.f('ix_llm_call_record_correlation_id'), table_name='llm_call_record')
    op.drop_table('llm_call_record')
    # ### end Alembic commands ###
